### PR TITLE
Use real bounding box tests for GetCollidedObjects

### PR DESCRIPTION
**Pull request by Lwmte**
This PR makes collision tests between objects which utilize `GetCollidedObjects` function much more reliable by using real bounding box tests instead of legacy method.

This also fixes lua API collision callbacks.

Things to test:

- projectile collision (grenades, rockets, flares, thrown burning torches)
- collision with objects and statics when shimmying and trying to climb (e.g. if object or static blocks further shimmying or climbing up)
- pole collision - if Lara still grabs and climbs pole correctly
- pickup collision - do multi pickups still work? do pickups work at all in various setups?
- flame emitters - do they burn Lara and enemies?
- pushables - are they still blocked by other moveables/statics?
- cleaner robot and spiky wall - do they still cause damage to Lara?

### CODE REVIEW

**Comment by Jakub768** [comment]
The function now works properly with a performance trade off it seems. Builders should optimize it themselves if they want to use the callbacks with lots of objects.

**Review by Jakub768 — APPROVED** [review]

**Review by Stranger1992 — CHANGES_REQUESTED** [review]
Tested:

### projectile collision (grenades, rockets, flares, thrown burning torches)

Result: hit and miss. As see below Lara will more than likely fail when using rocket launcher:

https://github.com/MontyTRC89/TombEngine/assets/84292688/bc2e8921-24cb-434c-8f51-16fe35c619b2

Super grenades are working. I don't know if this is just me but it does seem harder to get an accurate shot on the enemy.

https://github.com/MontyTRC89/TombEngine/assets/84292688/27ed24cf-e111-4ca0-bbf1-205c044f8386

Normal grenades work fine

https://github.com/MontyTRC89/TombEngine/assets/84292688/af5fa3a2-5065-461f-ba0d-b5222987528d

###  collision with objects and statics when shimmying and trying to climb (e.g. if object or static blocks further shimmying or climbing up) 

Working nicely! 

https://github.com/MontyTRC89/TombEngine/assets/84292688/7a53bb46-896c-4142-a2da-ae75f374dd11

pole collision - if Lara still grabs and climbs pole correctly

* Lara doesn't grab onto the pole if she is near it.
* Lara cannot climb up the pole when multiple pole objects are stacked up to extend the length of the pole. 

https://github.com/MontyTRC89/TombEngine/assets/84292688/6ee1cdc1-07fc-4fa7-b1f8-ef4f285978ec

### pickup collision - do multi pickups still work? do pickups work at all in various setups?

Multi-pick up works still. I haven't tested other setups at the moment. 

https://github.com/MontyTRC89/TombEngine/assets/84292688/4e390ffd-475e-4d40-a5f9-c52cda3e52ef

flame emitters - do they burn Lara and enemies?

Yes. 

https://github.com/MontyTRC89/TombEngine/assets/84292688/5d0964c8-f47b-4923-adba-050ab75482a2

pushables - are they still blocked by other moveables/statics?

Yes. I have a video that is too big for GH that shows the way blocked by the `ID_SAS_DRAG_BLOKE`  and Lara cannot push a block over him. 

image

**Comment by Jakub768** [comment]
- cleaner robot and spiky wall - do they still cause damage to Lara?

Yes.

- pushables - are they still blocked by other moveables/statics?

I have this problem in Develop, but otherwise it works as in Develop branch,

- pickup collision - do multi pickups still work? do pickups work at all in various setups?

Yes

flame emitters - do they burn Lara and enemies?

Yes

**Comment by Stranger1992** [comment]
Round 2 tests:

# Failed tests from last testing re-review

### Pole-rope collision: 

Success! Lara now will climb up to the ceiling and slide down with no issue (notice the collision box appearing)

https://github.com/MontyTRC89/TombEngine/assets/84292688/8599c811-2aa4-4de7-8ed7-a8b66b383e1c

### Rocket Launcher instant explode

Fixed! Previously rockets would explode immediately if Lara fired them whilst running. This now does not happen.

https://github.com/MontyTRC89/TombEngine/assets/84292688/afd6599d-a81a-44a0-b329-d6b1ef113c35

**Review by Stranger1992 — APPROVED** [review]
If there are further tests required then I will revoke this approval but if not, I approve!

**Review by Jakub768 — APPROVED** [review]

**Comment by Jakub768** [comment]
image
I now get these errors when trying to call "SetOnCollidewdWithObjects"

**Review by Jakub768 — CHANGES_REQUESTED** [review]
see above

**Review by Jakub768 — APPROVED** [review]

**Review by Sezzary — APPROVED** [review]

**Pull request merged**
