### PR TITLE
Animation refactors tier 2

### PR DESCRIPTION
**Pull request by Sezzary**
Tier 2 of around 5.
Introduces new `SetAnimation()` overload which allows for easy setting of animations from different slots.

To test:
- All vehicles (mounts, dismounts, deaths).
- Special creature deaths (TR1 torso boss, shiva, etc.).
- Any other special animations.
- Try killing various creature entities and see if they crash the game.

### CODE REVIEW

**Comment by Sezzary** [comment]
Okay done, nothing more will be pushed except to fix any bugs found.

**Comment by Kubsy** [comment]
I will be testing tomorrow

**Comment by Stranger1992** [comment]
https://user-images.githubusercontent.com/84292688/229627702-e40301a8-6ec0-421f-9992-66fd24977ab0.mp4

If Minecart is parked on an angle, it loses its collision after lara dismounts and cannot be used again.

**Comment by Stranger1992** [comment]
Killing the ID_GUARD will crash the game. I tested this with all weapons to the same result:


https://user-images.githubusercontent.com/84292688/229628142-0a2b7aa5-c015-41a8-9945-00f916c7bb10.mp4

**Comment by Stranger1992** [comment]
https://user-images.githubusercontent.com/84292688/229630024-5d714857-4f1f-49ce-8c42-039ac3a5266b.mp4

This one I cannot quite describe but the jeep is really erratic on complicated terrain with lots of slopes and ramps. Will slide about and jump up to places it shouldn't.

This video was using this terrain:

image

**Review by Kubsy — APPROVED** [review]

**Pull request merged**
